# Generated by Django 2.1.1 on 2018-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portarias', '0002_auto_20180906_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantes',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='visitantes',
            name='cor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='objetos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição de Objetos'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='placa',
            field=models.CharField(blank=True, max_length=8, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='placa_reboque',
            field=models.CharField(blank=True, max_length=8, verbose_name='Placa do Reboque'),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='tipo_veiculo',
            field=models.CharField(blank=True, choices=[('CAMINHÃO', 'Caminhão'), ('CARRETA', 'Carreta'), ('CARRO', 'Carro'), ('MOTO', 'Moto'), ('REBOQUE', 'Reboque')], max_length=10, verbose_name='Tipo de Veiculo'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='rg',
            field=models.CharField(blank=True, max_length=11, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.DeleteModel(
            name='Veiculos',
        ),
    ]
