# Generated by Django 2.1.1 on 2018-09-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portarias', '0004_crachas_visitante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitantes',
            options={'verbose_name': 'Portarias', 'verbose_name_plural': 'Portarias'},
        ),
    ]
